print(1)
raise Exception()
